{"name": "Test login failure due to incorrect credentials", "status": "passed", "start": 1734703515514, "stop": 1734703515516, "uuid": "950e89ae-06cd-4a63-a803-31bbddef9090", "historyId": "af0c221f5b263385674b49c2b66143ee", "testCaseId": "af0c221f5b263385674b49c2b66143ee", "fullName": "tests.couriers.test_courier_login#test_login_failure", "labels": [{"name": "feature", "value": "Courier Login"}, {"name": "story", "value": "Login Failure"}, {"name": "parentSuite", "value": "tests.couriers"}, {"name": "suite", "value": "test_courier_login"}, {"name": "host", "value": "KZALANB019"}, {"name": "thread", "value": "11352-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.couriers.test_courier_login"}]}