{"name": "Test login failure due to incorrect credentials", "status": "passed", "start": 1734711815839, "stop": 1734711815839, "uuid": "24f977bd-8561-4cf7-862d-87ff897977bc", "historyId": "af0c221f5b263385674b49c2b66143ee", "testCaseId": "af0c221f5b263385674b49c2b66143ee", "fullName": "tests.couriers.test_courier_login#test_login_failure", "labels": [{"name": "feature", "value": "Courier Login"}, {"name": "story", "value": "Login Failure"}, {"name": "parentSuite", "value": "tests.couriers"}, {"name": "suite", "value": "test_courier_login"}, {"name": "host", "value": "KZALANB019"}, {"name": "thread", "value": "18596-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.couriers.test_courier_login"}]}